Add requests to requirements-to-freeze.txt
The requests library is used by `trillian/trillian_log.py`, and without
adding it as a dependency, trying to install and use the trillian
library will result in the following error:

```python
>>> import trillian
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "trillian-demo-python-api-client/trillian/__init__.py", line 1, in <module>
    from .trillian_log import TrillianLog
  File "trillian-demo-python-api-client/trillian/trillian_log.py", line 4, in <module>
    import requests
ImportError: No module named requests
```